### PR TITLE
Spanish translation - Minor corrections.

### PR DESCRIPTION
**Pull request by Zeioth**
Include the changes proposed here:
https://github.com/Shatur95/optimus-manager-qt/pull/9#issuecomment-485241047

### CODE REVIEW

**Comment by Shatur** [comment]
I created the project page in [Transifex](https://www.transifex.com/optimus-manager-qt/optimus-manager-qt/dashboard/). You might want to be a collaborator :)

**Comment by Zeioth** [comment]
That link brings me to a 404 error.

**Comment by Shatur** [comment]
Oh, sorry. Just fixed :)

**Comment by Zeioth** [comment]
Ok I see transifex is working fine now. I'll translate everything during the next hours.

**Comment by Shatur** [comment]
Great!

**Comment by Zeioth** [comment]
Well that should be all! Cheers.

**Pull request merged**
