### PR TITLE
Resync translation files, made Hungarian full translation

### PR DESCRIPTION
**Pull request by blackPantherOS**
Please check and merge if you want

### CODE REVIEW

**Comment by Shatur** [comment]
Hi! Could you send only changes from `data/translations/optimus-manager-qt.ts ` and ` data/translations/optimus-manager-qt_hu.ts `?

**Comment by blackPantherOS** [comment]
> you send only changes from `data/translations/optimus-manager-qt.ts ` and `data/translations/optimus-manager-qt_hu.ts`?

No. all ts files are updated and sent as pull request. you can view after you pressed "Load diff" link
image

**Comment by Shatur** [comment]
> No. all ts files are updated and sent as pull request. you can view after you pressed "Load diff" link

Sure, I meant can you please remove other changes exept `data/translations/optimus-manager-qt.ts` and `data/translations/optimus-manager-qt_hu.ts`?

**Comment by blackPantherOS** [comment]
> Sure, I meant can you please remove other changes exept `data/translations/optimus-manager-qt.ts` and `data/translations/optimus-manager-qt_hu.ts`?

I don't know now, how I can undo couple item from full requests, and no understand why good for you, but I think so, you can reject my pull-requests and I will resend with these two item

**Comment by Shatur** [comment]
> I don't know now, how I can undo couple item from full requests, and no understand why good for you, but I think so, you can reject my pull-requests and I will resend with these two item

Okay, don't worry, I will do it myself today after work :)
Due to the integration with Crowdin, other languages ​​differ in indentation (since Crowdin does them a little differently). So, it is better to send only the translation file itself, which has changed, and `data / translations / optimus-manager-qt.ts`. Crowdin will update the rest of the languages ​​automatically.

**Comment by Shatur** [comment]
Done, thanks!

**Pull request merged**
